# Supply Chain Analytics

In [58]:
import pandas as pd

In [60]:
def read_file(path):
    """Read a CSV file and return a DataFrame."""

    if not path:
        raise ValueError("File path cannot be empty.")

    try:
        return pd.read_csv(path)

    except Exception as error:
        print(f"Error reading file: {error}")
        return None

In [89]:
def save_file(df, path):
    """Save a DataFrame to a CSV file."""

    df.to_csv(path, index=False)
    print(f"File saved successfully: {path}")

In [61]:
def get_data_quality_report(df):
    """Generate a basic data quality report."""

    report = pd.DataFrame({
        "Missing Values": df.isnull().sum(),
        "Missing %": (df.isnull().mean() * 100).round(2),
        "Unique Values": df.nunique(),
    })

    print(f"Total Rows: {df.shape[0]}")
    print(f"Total Columns: {df.shape[1]}")
    print(f"Duplicate Rows: {df.duplicated().sum()}")
    print(f"Data Types:\n{df.dtypes}")


    return report

In [62]:
def check_value_counts(df, columns=None):
    """Display value counts for selected columns."""
    if columns is None:
        columns = df.columns

    for col in columns:
        if col in df.columns:
            print(f"\n{col} Value Counts:")
            print(df[col].value_counts())
        else:
            print(f"Column not found: {col}")

In [63]:
files = [
    "dim_customer",
    "dim_date",
    "dim_facility",
    "dim_product",
    "dim_supplier",
    "fact_inventory",
    "fact_procurement",
    "fact_production",
    "fact_sales",
    "fact_shipment",
]

In [ ]:
dataframes = {}

for col in files:
    dataframes[col] = read_file(f"../data/raw/{col}.csv")
    print(f"Loaded file: {col}")

In [65]:
dataframes["dim_customer"]

,customer_id,customer_key,customer_name,country,channel_type,size,annual_volume_usd
0,1,CUST-US-AMZ-001,Amazon.com Inc.,USA,Online,Large,1200000000
1,2,CUST-US-BBY-001,Best Buy Co. Inc.,USA,Retailer,Large,850000000
2,3,CUST-EU-MMK-001,MediaMarkt Saturn,Germany,Retailer,Large,450000000
3,4,CUST-IN-FLP-001,Flipkart,India,Online,Large,420000000
4,5,CUST-KR-SSD-001,Samsung Direct Store,South Korea,Direct,Large,650000000

In [67]:
get_data_quality_report(dataframes["dim_customer"])

Total Rows: 5
Total Columns: 7
Duplicate Rows: 0
Data Types:
customer_id          int64
customer_key           str
customer_name          str
country                str
channel_type           str
size                   str
annual_volume_usd    int64
dtype: object

                   Missing Values  Missing %  Unique Values
customer_id                     0        0.0              5
customer_key                    0        0.0              5
customer_name                   0        0.0              5
country                         0        0.0              4
channel_type                    0        0.0              3
size                            0        0.0              1
annual_volume_usd               0        0.0              5

In [66]:
check_value_counts(dataframes["dim_customer"], ["country", "channel_type","size"])

country Value Counts:
country
USA            2
Germany        1
India          1
South Korea    1
Name: count, dtype: int64

channel_type Value Counts:
channel_type
Online      2
Retailer    2
Direct      1
Name: count, dtype: int64

size Value Counts:
size
Large    5
Name: count, dtype: int64

In [71]:
get_data_quality_report(dataframes["dim_date"])

Total Rows: 731
Total Columns: 11
Duplicate Rows: 0
Data Types:
date_key       int64
date             str
year           int64
quarter        int64
month          int64
month_name       str
week           int64
day            int64
day_of_week    int64
day_name         str
is_weekend     int64
dtype: object

             Missing Values  Missing %  Unique Values
date_key                  0        0.0            731
date                      0        0.0            731
year                      0        0.0              2
quarter                   0        0.0              4
month                     0        0.0             12
month_name                0        0.0             12
week                      0        0.0             52
day                       0        0.0             31
day_of_week               0        0.0              7
day_name                  0        0.0              7
is_weekend                0        0.0              2

In [75]:
check_value_counts(dataframes["dim_date"], ['year',"day_name"])

year Value Counts:
year
2024    366
2023    365
Name: count, dtype: int64

day_name Value Counts:
day_name
Sunday       105
Monday       105
Tuesday      105
Wednesday    104
Thursday     104
Friday       104
Saturday     104
Name: count, dtype: int64

In [76]:
dataframes["dim_facility"]

,facility_id,facility_key,facility_name,country,city,facility_type,specialization,annual_capacity
0,1,FAC-KR-GUM-P1,Gumi Manufacturing 1,South Korea,Gumi,Manufacturing,Smartphone,850000
1,2,FAC-VN-TNG-P1,Thai Nguyen Plant,Vietnam,Thai Nguyen,Manufacturing,Mobile Assembly,1500000
2,3,FAC-KR-GUM-P3,Gumi Appliance Plant,South Korea,Gumi,Manufacturing,Appliances,320000
3,4,WH-US-NJ-DC1,New Jersey DC,USA,Cranbury,Warehouse,North America,500000
4,5,WH-EU-PL-DC1,Poland DC,Poland,Warsaw,Warehouse,Europe,520000
5,6,WH-IN-MUM-DC1,Mumbai DC,India,Mumbai,Warehouse,India,550000

In [77]:
get_data_quality_report(dataframes["dim_facility"])

Total Rows: 6
Total Columns: 8
Duplicate Rows: 0
Data Types:
facility_id        int64
facility_key         str
facility_name        str
country              str
city                 str
facility_type        str
specialization       str
annual_capacity    int64
dtype: object

                 Missing Values  Missing %  Unique Values
facility_id                   0        0.0              6
facility_key                  0        0.0              6
facility_name                 0        0.0              6
country                       0        0.0              5
city                          0        0.0              5
facility_type                 0        0.0              2
specialization                0        0.0              6
annual_capacity               0        0.0              6

In [78]:
dataframes["dim_product"]

,product_id,product_key,product_name,category,product_line,spec,color,unit_price,unit_cost,weight_kg,Img
0,1,SM-S928UZKAXAA,Galaxy S24 Ultra,Smartphone,Galaxy S,512GB,Phantom Black,1299.99,899.99,0.21,https://i.ibb.co/9Hv19S22/s24-Ultra.webp
1,2,SM-S928UZAAXAA,Galaxy S24 Ultra,Smartphone,Galaxy S,256GB,Titanium Gray,1199.99,839.99,0.15,https://i.ibb.co/9Hv19S22/s24-Ultra.webp
2,3,SM-S921ULVAXAA,Galaxy S24,Smartphone,Galaxy S,256GB,Cobalt Violet,849.99,594.99,0.18,https://i.ibb.co/gMJgXrhG/s24.webp
3,4,SM-S911UCEAXAA,Galaxy S23,Smartphone,Galaxy S,128GB,Cream,699.99,489.99,0.17,https://i.ibb.co/tPH2nTkP/s23.webp
4,5,SM-F946UZKAXAA,Galaxy Z Fold5,Smartphone,Galaxy Z,512GB,Phantom Black,1919.99,1343.99,0.22,https://i.ibb.co/tPnpz3yp/Folf5.webp
5,6,SM-F731UZKAXAA,Galaxy Z Flip5,Smartphone,Galaxy Z,256GB,Graphite,999.99,699.99,0.22,https://i.ibb.co/kgXHN1Nh/fold-5-2.webp
6,7,SM-X916UZAAXAA,Galaxy Tab S9 Ultra,Tablet,Tab S,512GB,Graphite,1319.99,923.99,0.67,https://i.ibb.co/HDYmTQ8b/a54.webp
7,8,SM-X810NZAAXAR,Galaxy Tab S9,Tablet,Tab S,256GB,Graphite,899.99,629.99,0.47,https://i.ibb.co/F4br0pKx/a34.webp
8,9,SM-X115NZAAXAR,Galaxy Tab A9,Tablet,Tab A,64GB,Graphite,219.99,153.99,0.56,https://i.ibb.co/v6MTK3p6/s9.webp
9,10,QN85QN90DAFXZA,"Neo QLED 85"" 4K",Television,Neo QLED,85 inch,Black,3299.99,2144.99,15.89,https://i.ibb.co/Xf1xx78G/tab-s9-ultra.webp
10,11,QN65S90DAFXZA,"OLED 65"" 4K",Television,OLED,65 inch,Black,2299.99,1494.99,21.56,https://i.ibb.co/p67NdXxW/tab-a9.webp
11,12,UN65CU8000FXZA,"Crystal UHD 65""",Television,Crystal UHD,65 inch,Black,649.99,422.49,30.16,https://i.ibb.co/MDMdXTmG/q-85.webp
12,13,RF28T5A01SR/AA,Family Hub Refrigerator,Appliance,Refrigerator,28 cu ft,Stainless Steel,3299.99,2144.99,52.65,https://i.ibb.co/KzKrmT0s/q-75.webp
13,14,WF50A8800AV/US,Smart Front Load Washer,Appliance,Washer,5.0 cu ft,Brushed Black,1299.99,844.99,69.88,https://i.ibb.co/mw7XszY/q-65.webp
14,15,SM-R960NZKAXAA,Galaxy Watch6 Classic,Wearable,Watch,47mm,Black,429.99,300.99,0.06,https://i.ibb.co/nsB3JCLs/Crystal-UHD-55.webp
15,16,SM-R510NZAAXAR,Galaxy Buds2 Pro,Wearable,Earbuds,Standard,Graphite,229.99,160.99,0.06,https://i.ibb.co/N2MSq6ZX/Family-Hub-Refrigera...

In [79]:
get_data_quality_report(dataframes["dim_product"])

Total Rows: 16
Total Columns: 11
Duplicate Rows: 0
Data Types:
product_id        int64
product_key         str
product_name        str
category            str
product_line        str
spec                str
color               str
unit_price      float64
unit_cost       float64
weight_kg       float64
Img                 str
dtype: object

              Missing Values  Missing %  Unique Values
product_id                 0        0.0             16
product_key                0        0.0             16
product_name               0        0.0             15
category                   0        0.0              5
product_line               0        0.0             11
spec                       0        0.0             10
color                      0        0.0              8
unit_price                 0        0.0             14
unit_cost                  0        0.0             15
weight_kg                  0        0.0             14
Img                        0        0.0             15

In [80]:
dataframes["dim_supplier"]

,supplier_id,supplier_key,supplier_name,country,city,specialty,tier,avg_quality_score
0,1,SUP-KR-SEC-001,Samsung Electronics Co. Ltd,South Korea,Seoul,Integrated Components,Tier 1,98.5
1,2,SUP-KR-SKH-002,SK Hynix Inc.,South Korea,Icheon,DRAM & NAND Flash,Tier 1,97.8
2,3,SUP-TW-TSM-001,Taiwan Semiconductor Mfg,Taiwan,Hsinchu,Processors,Tier 1,99.2
3,4,SUP-JP-SON-001,Sony Semiconductor,Japan,Tokyo,Image Sensors,Tier 1,98.9
4,5,SUP-CN-BOE-001,BOE Technology,China,Beijing,Display Panels,Tier 1,96.5
5,6,SUP-VN-SEV-001,Samsung Vietnam,Vietnam,Thai Nguyen,Final Assembly,Tier 2,96.8
6,7,SUP-IN-SEI-001,Samsung India,India,Noida,Regional Assembly,Tier 2,95.9

In [81]:
get_data_quality_report(dataframes["dim_product"])

Total Rows: 16
Total Columns: 11
Duplicate Rows: 0
Data Types:
product_id        int64
product_key         str
product_name        str
category            str
product_line        str
spec                str
color               str
unit_price      float64
unit_cost       float64
weight_kg       float64
Img                 str
dtype: object

              Missing Values  Missing %  Unique Values
product_id                 0        0.0             16
product_key                0        0.0             16
product_name               0        0.0             15
category                   0        0.0              5
product_line               0        0.0             11
spec                       0        0.0             10
color                      0        0.0              8
unit_price                 0        0.0             14
unit_cost                  0        0.0             15
weight_kg                  0        0.0             14
Img                        0        0.0             15

In [82]:
dataframes["fact_inventory"]

,inventory_id,date_key,product_id,facility_id,stock_level,safety_stock_level,reorder_point
0,1,31,1,4,138,53,88
1,2,31,1,5,121,53,88
2,3,31,1,6,127,53,88
3,4,31,2,4,232,113,145
4,5,31,2,5,266,113,145
...,...,...,...,...,...,...,...
1147,1148,731,15,5,440,206,249
1148,1149,731,15,6,395,206,249
1149,1150,731,16,4,328,163,347
1150,1151,731,16,5,503,163,347
1151,1152,731,16,6,515,163,347

In [83]:
get_data_quality_report(dataframes["fact_inventory"])

Total Rows: 1152
Total Columns: 7
Duplicate Rows: 0
Data Types:
inventory_id          int64
date_key              int64
product_id            int64
facility_id           int64
stock_level           int64
safety_stock_level    int64
reorder_point         int64
dtype: object

                    Missing Values  Missing %  Unique Values
inventory_id                     0        0.0           1152
date_key                         0        0.0             24
product_id                       0        0.0             16
facility_id                      0        0.0              3
stock_level                      0        0.0            354
safety_stock_level               0        0.0            160
reorder_point                    0        0.0            210

In [84]:
dataframes["fact_procurement"]

,procurement_id,order_date_key,product_id,supplier_id,order_quantity,unit_cost,total_cost,lead_time_days,delivery_date_key,quality_score,po_number
0,1,646,15,6,53,199.23,10559.19,12,658,94.9,PO-2024-294458
1,2,651,7,1,50,636.67,31833.50,17,668,96.9,PO-2024-189045
2,3,632,16,3,121,120.73,14608.33,13,645,98.0,PO-2024-394238
3,4,62,12,1,50,285.66,14283.00,8,70,98.4,PO-2023-777368
4,5,315,13,4,50,1587.75,79387.50,16,331,98.6,PO-2023-137156
...,...,...,...,...,...,...,...,...,...,...,...
2195,2196,584,6,5,52,485.79,25261.08,12,596,94.1,PO-2024-686349
2196,2197,133,9,6,50,114.85,5742.50,7,140,96.3,PO-2023-106917
2197,2198,506,1,2,56,629.51,35252.56,11,517,94.9,PO-2024-808738
2198,2199,678,15,5,161,223.75,36023.75,16,694,95.6,PO-2024-633546
2199,2200,225,1,5,50,665.95,33297.50,12,237,93.5,PO-2023-829665

In [85]:
get_data_quality_report(dataframes["fact_procurement"])

Total Rows: 2200
Total Columns: 11
Duplicate Rows: 0
Data Types:
procurement_id         int64
order_date_key         int64
product_id             int64
supplier_id            int64
order_quantity         int64
unit_cost            float64
total_cost           float64
lead_time_days         int64
delivery_date_key      int64
quality_score        float64
po_number                str
dtype: object

                   Missing Values  Missing %  Unique Values
procurement_id                  0        0.0           2200
order_date_key                  0        0.0            687
product_id                      0        0.0             16
supplier_id                     0        0.0              7
order_quantity                  0        0.0            123
unit_cost                       0        0.0           2160
total_cost                      0        0.0           2175
lead_time_days                  0        0.0             14
delivery_date_key               0        0.0            692
quality_score                   0        0.0             72
po_number                       0        0.0           2197

In [ ]:
dataframes["fact_production"]

In [86]:
get_data_quality_report(dataframes["fact_production"])

Total Rows: 4500
Total Columns: 8
Duplicate Rows: 0
Data Types:
production_id          int64
date_key               int64
product_id             int64
facility_id            int64
quantity_produced      int64
defective_units        int64
defect_rate_pct      float64
batch_number             str
dtype: object

                   Missing Values  Missing %  Unique Values
production_id                   0        0.0           4500
date_key                        0        0.0            728
product_id                      0        0.0             16
facility_id                     0        0.0              3
quantity_produced               0        0.0           1563
defective_units                 0        0.0             54
defect_rate_pct                 0        0.0            106
batch_number                    0        0.0           4461

In [ ]:
dataframes["fact_sales"]

In [87]:
get_data_quality_report(dataframes["fact_sales"])

Total Rows: 8500
Total Columns: 14
Duplicate Rows: 0
Data Types:
sales_id               int64
date_key               int64
product_id             int64
customer_id            int64
quantity_sold          int64
unit_price           float64
discount_pct           int64
discount_amount      float64
gross_revenue        float64
net_revenue          float64
total_cost           float64
profit               float64
profit_margin_pct    float64
order_number             str
dtype: object

                   Missing Values  Missing %  Unique Values
sales_id                        0        0.0           8500
date_key                        0        0.0            731
product_id                      0        0.0             16
customer_id                     0        0.0              5
quantity_sold                   0        0.0            110
unit_price                      0        0.0             14
discount_pct                    0        0.0              6
discount_amount                 0        0.0           1261
gross_revenue                   0        0.0            800
net_revenue                     0        0.0           2319
total_cost                      0        0.0            816
profit                          0        0.0           2275
profit_margin_pct               0        0.0             18
order_number                    0        0.0           8499

In [ ]:
dataframes["fact_shipment"]

In [88]:
get_data_quality_report(dataframes["fact_shipment"])

Total Rows: 7500
Total Columns: 13
Duplicate Rows: 0
Data Types:
shipment_id            int64
ship_date_key          int64
delivery_date_key      int64
product_id             int64
facility_id            int64
customer_id            int64
quantity               int64
carrier                  str
status                   str
shipping_cost        float64
total_weight_kg      float64
tracking_number          str
delay_reason             str
dtype: object

                   Missing Values  Missing %  Unique Values
shipment_id                     0       0.00           7500
ship_date_key                   0       0.00            731
delivery_date_key               0       0.00            725
product_id                      0       0.00             36
facility_id                     0       0.00              7
customer_id                     0       0.00             17
quantity                        0       0.00           1141
carrier                         0       0.00              9
status                          0       0.00              4
shipping_cost                   0       0.00           7395
total_weight_kg                 0       0.00           4788
tracking_number                 0       0.00           7500
delay_reason                 6927      92.36              8

In [91]:
for col in files:
    save_file(
        dataframes[col],
        f"../data/processed/{col}.csv"
    )

File saved successfully: ../data/processed/dim_customer.csv
File saved successfully: ../data/processed/dim_date.csv
File saved successfully: ../data/processed/dim_facility.csv
File saved successfully: ../data/processed/dim_product.csv
File saved successfully: ../data/processed/dim_supplier.csv
File saved successfully: ../data/processed/fact_inventory.csv
File saved successfully: ../data/processed/fact_procurement.csv
File saved successfully: ../data/processed/fact_production.csv
File saved successfully: ../data/processed/fact_sales.csv
File saved successfully: ../data/processed/fact_shipment.csv